### ISSUE TITLE
Problem starting the bot

### ISSUE THREAD

**Issue by Jagermo** [elliottwilliams/mumbletune#16]
Hi there, I'm running the bot on Ubuntu 14.04 LTS (all depedencies are installed, however i used older versions of libcelt-dev), but I'm having trouble starting it

Here is the error output:

```
user@pc~/mumblebot/mumbletune/bin$ ./mumbletune -c conf.mumble.yaml

/home/user/mumblebot/mumbletune/lib/mumbletune/hallon_player.rb:27:in `read': No such file or directory - /home/user/mumblebot/mubletune/spotify_appkey.key (Errno::ENOENT)
        from /home/user/mumblebot/mumbletune/lib/mumbletune/hallon_player.rb:27:in `connect'
        from /home/user/mumblebot/mumbletune/lib/mumbletune.rb:51:in `block in <module:Mumbletune>'

```

Anyone got an idea? 

So far I did add the path to the spotifykey-file (its a premium account) but I did not enter the user and passwort (as it is my brothers FB account and I don't want to bear that responsibility).

**Comment by elliottwilliams** [comment]
Hey! from the looks of it, mumbletune cannot load the API key to connect to Spotify. Can you verify that this file exists on your machine?

/home/user/mumblebot/mubletune/spotify_appkey.key

You'll get an authentication error until you enter a valid username and password, but that exception will come from a different part of the code.

**Comment by Jagermo** [comment]
Ok, I'll keep trying, thanks.
