### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by ghost** [elliottwilliams/mumbletune#3]
What's going on here? How can I fix this?
https://gist.github.com

Thanks!

**Comment by elliottwilliams** [comment]
Hm, that's interesting. It appears to be a problem with the underlying library that connects to Mumble.

Have you tried using a different Ruby version? There may be an incompatibility with 2.0. I use MRI Ruby 1.9.3 on my server. It'd also help to know what OS and version you're working off of.

If you use [RVM](http://rvm.io) to manage ruby versions, you can install with:

```
$ rvm install 1.9.3
$ rvm use 1.9.3
```

On Ubuntu, I know there is a package `ruby1.9.3` that'll also work.

Good luck! And thanks for being patient—school has been keeping me busy :smile:

**Comment by elliottwilliams** [comment]
Awesome! That is definitely a bug I can reproduce, thank you for catching it!

For clarity's sake I've started #4 to track it from here on out.
